#!/usr/bin/env ruby

require "active_support/core_ext/string/inflections"
require "fileutils"
require "debug"
require_relative "./commands/generate_parameter_validator"

include GenerateValidator

COMMAND = ARGV.shift
NAME    = ARGV.shift&.downcase


def check_inflection(name)
  app_root = defined?(Rails) ? Rails.root : Dir.pwd
  inflection_path = File.join(app_root, 'config', 'initializers', 'inflections.rb')

  require inflection_path if File.exist?(inflection_path)
  if ActiveSupport::Inflector.inflections.acronyms.key?("api")
    'API'
  else
    'Api'
  end
end

case COMMAND
when "generate"
  if NAME.nil?
    puts "❌ Please provide a name. Example: rails_validation_api generate purchaseorder"
  else
    generate_parameter_validator(NAME)
    generate_validator(NAME)
  end
when "destroy"
  if NAME.nil?
     puts "❌ Please provide a name. Example: rails_validation_api generate purchaseorder"
  else
    destroy_validator(NAME)
  end
else
  usage
end
